services:

  galactic-science-opm:
    restart: unless-stopped
    volumes: !override
      - ${DJANGO_STATIC_DIR:-./_static}:/galactic_science_opm/_static
      - ${DJANGO_DATA_DIR:-./data}:/galactic_science_opm/data
      - .:/galactic_science_opm
    ports:
      - "${EXT_PORT:-8000}:8000"
    environment:
     LOCAL: 1
     DJANGO_DEBUG: True
