FROM python:3.11-slim
LABEL maintainer="llindstrom@lco.global"
LABEL maintainer="markus.hundertmark@uni-heidelberg.de"

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /galactic_science_opm

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*
    
RUN pip install --upgrade pip && pip install 'poetry >=2.0,<3.0'

COPY pyproject.toml poetry.lock /galactic_science_opm/

# tell poetry: do NOT create a virtual env; should install everything globally
# tell poetry: even if you find a virtual env, don't use it; install everything globally
# now have poetry install dependencies according to pyproject.toml
RUN poetry config virtualenvs.create false --local && \
poetry config virtualenvs.in-project false --local && \
poetry lock && \
poetry install -vv --no-interaction && \
poetry run playwright install --with-deps

COPY . .  

RUN chmod +x /galactic_science_opm/entrypoint.sh
RUN chmod +x /galactic_science_opm/wait-for-healthy.sh
CMD ["/galactic_science_opm/entrypoint.sh"]
