FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*
    
RUN pip install --upgrade pip

RUN pip install pytest-playwright pytest-asyncio
RUN playwright install --with-deps

COPY . .  

RUN chmod +x /code/entrypoint.e2e.sh
RUN chmod +x /code/wait-for-healthy.sh
CMD ["/code/entrypoint.e2e.sh"]
