import random

from django.test import TestCase

from custom_code.helpers import create_and_attach_classifications_to_target
from custom_code.target_models import (
    ClassificationGeneralized,
    ClassificationSource,
    GalacticTarget,
)


probs = [
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "SNIa",
        "probability": 0.0136,
        "ranking": 14,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "SNIa",
        "probability": 1.4845295e-05,
        "ranking": 18,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "SNIa",
        "probability": 0.030024,
        "ranking": 12,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_periodic",
        "classifier_version": "2.1.0",
        "class_name": "LPV",
        "probability": 0.044,
        "ranking": 5,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_stochastic",
        "classifier_version": "2.1.0",
        "class_name": "Microlensing",
        "probability": 0.598,
        "ranking": 1,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_top",
        "classifier_version": "2.1.0",
        "class_name": "Transient",
        "probability": 0.278,
        "ranking": 3,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_transient",
        "classifier_version": "2.1.0",
        "class_name": "SNIa",
        "probability": 0.108,
        "ranking": 5,
    },
    {
        "classifier_name": "stamp_classifier",
        "classifier_version": "stamp_classifier_1.0.4",
        "class_name": "SN",
        "probability": 0.20702355,
        "ranking": 3,
    },
    {
        "classifier_name": "stamp_classifier_2025_beta",
        "classifier_version": "2.1.1_beta",
        "class_name": "SN",
        "probability": 0.0028256858,
        "ranking": 4,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "SNIbc",
        "probability": 0.026928,
        "ranking": 10,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "SNIbc",
        "probability": 5.382856e-05,
        "ranking": 16,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "SESN",
        "probability": 0.046148,
        "ranking": 8,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_periodic",
        "classifier_version": "2.1.0",
        "class_name": "EA",
        "probability": 0.15,
        "ranking": 2,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_stochastic",
        "classifier_version": "2.1.0",
        "class_name": "QSO",
        "probability": 0.028,
        "ranking": 6,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_top",
        "classifier_version": "2.1.0",
        "class_name": "Stochastic",
        "probability": 0.432,
        "ranking": 1,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_transient",
        "classifier_version": "2.1.0",
        "class_name": "SESN",
        "probability": 0.166,
        "ranking": 4,
    },
    {
        "classifier_name": "stamp_classifier",
        "classifier_version": "stamp_classifier_1.0.4",
        "class_name": "AGN",
        "probability": 0.25765607,
        "ranking": 2,
    },
    {
        "classifier_name": "stamp_classifier_2025_beta",
        "classifier_version": "2.1.1_beta",
        "class_name": "AGN",
        "probability": 0.08658924,
        "ranking": 2,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "SNII",
        "probability": 0.05712,
        "ranking": 5,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "SNII",
        "probability": 0.05838,
        "ranking": 6,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_periodic",
        "classifier_version": "2.1.0",
        "class_name": "EB/EW",
        "probability": 0.034,
        "ranking": 6,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_stochastic",
        "classifier_version": "2.1.0",
        "class_name": "AGN",
        "probability": 0.03,
        "ranking": 5,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_top",
        "classifier_version": "2.1.0",
        "class_name": "Periodic",
        "probability": 0.29,
        "ranking": 2,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_transient",
        "classifier_version": "2.1.0",
        "class_name": "SNII",
        "probability": 0.21,
        "ranking": 3,
    },
    {
        "classifier_name": "stamp_classifier",
        "classifier_version": "stamp_classifier_1.0.4",
        "class_name": "VS",
        "probability": 0.33924207,
        "ranking": 1,
    },
    {
        "classifier_name": "stamp_classifier_2025_beta",
        "classifier_version": "2.1.1_beta",
        "class_name": "VS",
        "probability": 0.90660954,
        "ranking": 1,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "SLSN",
        "probability": 0.038352,
        "ranking": 9,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "SNII",
        "probability": 0.02871585,
        "ranking": 8,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "SNIIn",
        "probability": 0.06116,
        "ranking": 4,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_periodic",
        "classifier_version": "2.1.0",
        "class_name": "Periodic-Other",
        "probability": 0.112,
        "ranking": 4,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_stochastic",
        "classifier_version": "2.1.0",
        "class_name": "Blazar",
        "probability": 0.06,
        "ranking": 4,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_transient",
        "classifier_version": "2.1.0",
        "class_name": "SNIIn",
        "probability": 0.22,
        "ranking": 1,
    },
    {
        "classifier_name": "stamp_classifier",
        "classifier_version": "stamp_classifier_1.0.4",
        "class_name": "asteroid",
        "probability": 0.044395946,
        "ranking": 5,
    },
    {
        "classifier_name": "stamp_classifier_2025_beta",
        "classifier_version": "2.1.1_beta",
        "class_name": "asteroid",
        "probability": 3.4435138e-07,
        "ranking": 6,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "QSO",
        "probability": 0.051512,
        "ranking": 6,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "SNIIn",
        "probability": 9.1172486e-05,
        "ranking": 15,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "SLSN",
        "probability": 0.059492,
        "ranking": 5,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_periodic",
        "classifier_version": "2.1.0",
        "class_name": "RSCVn",
        "probability": 0.43,
        "ranking": 1,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_stochastic",
        "classifier_version": "2.1.0",
        "class_name": "YSO",
        "probability": 0.166,
        "ranking": 2,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_transient",
        "classifier_version": "2.1.0",
        "class_name": "SLSN",
        "probability": 0.214,
        "ranking": 2,
    },
    {
        "classifier_name": "stamp_classifier",
        "classifier_version": "stamp_classifier_1.0.4",
        "class_name": "bogus",
        "probability": 0.15168248,
        "ranking": 4,
    },
    {
        "classifier_name": "stamp_classifier_2025_beta",
        "classifier_version": "2.1.1_beta",
        "class_name": "bogus",
        "probability": 0.0039390954,
        "ranking": 3,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "AGN",
        "probability": 0.020824,
        "ranking": 12,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "SLSN",
        "probability": 3.024859e-08,
        "ranking": 20,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "TDE",
        "probability": 0.022796,
        "ranking": 14,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_periodic",
        "classifier_version": "2.1.0",
        "class_name": "CEP",
        "probability": 0.138,
        "ranking": 3,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_stochastic",
        "classifier_version": "2.1.0",
        "class_name": "CV/Nova",
        "probability": 0.118,
        "ranking": 3,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_transient",
        "classifier_version": "2.1.0",
        "class_name": "TDE",
        "probability": 0.082,
        "ranking": 6,
    },
    {
        "classifier_name": "stamp_classifier_2025_beta",
        "classifier_version": "2.1.1_beta",
        "class_name": "satellite",
        "probability": 3.6094843e-05,
        "ranking": 5,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "Blazar",
        "probability": 0.041648,
        "ranking": 8,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "TDE",
        "probability": 3.0076116e-08,
        "ranking": 21,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "Microlensing",
        "probability": 0.258336,
        "ranking": 1,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_periodic",
        "classifier_version": "2.1.0",
        "class_name": "RRLab",
        "probability": 0.03,
        "ranking": 8,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "CV/Nova",
        "probability": 0.112888,
        "ranking": 3,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "Microlensing",
        "probability": 0.004617758,
        "ranking": 12,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "QSO",
        "probability": 0.012096,
        "ranking": 17,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_periodic",
        "classifier_version": "2.1.0",
        "class_name": "RRLc",
        "probability": 0.03,
        "ranking": 9,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "YSO",
        "probability": 0.321128,
        "ranking": 1,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "QSO",
        "probability": 4.428953e-05,
        "ranking": 17,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "AGN",
        "probability": 0.01296,
        "ranking": 15,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot_periodic",
        "classifier_version": "2.1.0",
        "class_name": "DSCT",
        "probability": 0.032,
        "ranking": 7,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "LPV",
        "probability": 0.00948,
        "ranking": 15,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "AGN",
        "probability": 0.0007806852,
        "ranking": 14,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "Blazar",
        "probability": 0.02592,
        "ranking": 13,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "E",
        "probability": 0.0632,
        "ranking": 4,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "Blazar",
        "probability": 0.04340668,
        "ranking": 5,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "YSO",
        "probability": 0.071712,
        "ranking": 3,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "DSCT",
        "probability": 0.0158,
        "ranking": 13,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "YSO",
        "probability": 0.10231948,
        "ranking": 4,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "CV/Nova",
        "probability": 0.050976,
        "ranking": 7,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "RRL",
        "probability": 0.0474,
        "ranking": 7,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "CV/Nova",
        "probability": 0.25304887,
        "ranking": 2,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "LPV",
        "probability": 0.01276,
        "ranking": 16,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "CEP",
        "probability": 0.02212,
        "ranking": 11,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "LPV",
        "probability": 0.18999334,
        "ranking": 3,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "EA",
        "probability": 0.0435,
        "ranking": 9,
    },
    {
        "classifier_name": "lc_classifier",
        "classifier_version": "lc_classifier_1.1.13",
        "class_name": "Periodic-Other",
        "probability": 0.158,
        "ranking": 2,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "EA",
        "probability": 0.27734745,
        "ranking": 1,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "EB/EW",
        "probability": 0.00986,
        "ranking": 18,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "EB/EW",
        "probability": 0.007217038,
        "ranking": 10,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "Periodic-Other",
        "probability": 0.03248,
        "ranking": 11,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "Periodic-Other",
        "probability": 3.492263e-08,
        "ranking": 19,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "RSCVn",
        "probability": 0.1247,
        "ranking": 2,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "RSCVn",
        "probability": 0.012362421,
        "ranking": 9,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "CEP",
        "probability": 0.04002,
        "ranking": 10,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "CEP",
        "probability": 0.037041847,
        "ranking": 6,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "RRLab",
        "probability": 0.0087,
        "ranking": 20,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "RRLab",
        "probability": 0.0061204024,
        "ranking": 11,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "RRLc",
        "probability": 0.0087,
        "ranking": 21,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "RRLc",
        "probability": 0.0022163135,
        "ranking": 13,
    },
    {
        "classifier_name": "lc_classifier_BHRF_forced_phot",
        "classifier_version": "2.1.0",
        "class_name": "DSCT",
        "probability": 0.00928,
        "ranking": 19,
    },
    {
        "classifier_name": "LC_classifier_ATAT_forced_phot(beta)",
        "classifier_version": "1.0.0",
        "class_name": "DSCT",
        "probability": 0.0346075,
        "ranking": 7,
    },
]


class AlerceClassificationParserTests(TestCase):

    def test_create_and_assign_classifications(self):

        # Given a target and probabilities from Alerce
        target = GalacticTarget.objects.create(name="ZTF26aatgnhu")

        # When we create classifications
        sources_new, classifications_new, classifications_updated = (
            create_and_attach_classifications_to_target(
                probabilities=probs, target=target
            )
        )

        # Then there should be new sources, new classifications and no updated ones
        self.assertGreater(a=len(classifications_new), b=0)
        self.assertGreater(a=len(sources_new), b=0)
        self.assertEqual(first=len(classifications_updated), second=0)

        # When we change the probabilities and try to attach again
        new_probs = [{**prob, **{"probability": random.uniform(0,1)}} for prob in probs]
        sources_new, classifications_new, classifications_updated = (
            create_and_attach_classifications_to_target(
                probabilities=new_probs, target=target
            )
        )

        # Then there should be no new sources or classifications, but updated ones
        self.assertEqual(first=len(classifications_new), second=0)
        self.assertEqual(first=len(sources_new), second=0)
        self.assertGreater(a=len(classifications_updated), b=0)
