# Generated by Django 4.2.25 on 2025-11-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tom_targets', '0029_alter_basetarget_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('class1', models.CharField(max_length=50)),
                ('prob_class1', models.FloatField(default=0, null=True)),
                ('class2', models.CharField(max_length=50, null=True)),
                ('prob_class2', models.FloatField(default=0, null=True)),
                ('class3', models.CharField(max_length=50, null=True)),
                ('prob_class3', models.FloatField(default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalacticTarget',
            fields=[
                ('basetarget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tom_targets.basetarget')),
                ('base_u_mag', models.FloatField(default=0)),
                ('err_u_mag', models.FloatField(default=0)),
                ('base_g_mag', models.FloatField(default=0)),
                ('err_g_mag', models.FloatField(default=0)),
                ('base_r_mag', models.FloatField(default=0)),
                ('err_r_mag', models.FloatField(default=0)),
                ('base_i_mag', models.FloatField(default=0)),
                ('err_i_mag', models.FloatField(default=0)),
                ('base_z_mag', models.FloatField(default=0)),
                ('err_z_mag', models.FloatField(default=0)),
                ('base_y_mag', models.FloatField(default=0)),
                ('err_y_mag', models.FloatField(default=0)),
                ('target_type', models.CharField(default='Microlensing candidate', max_length=50)),
            ],
            options={
                'verbose_name': 'target',
                'permissions': (('view_target', 'View Target'), ('add_target', 'Add Target'), ('change_target', 'Change Target'), ('delete_target', 'Delete Target')),
            },
            bases=('tom_targets.basetarget',),
        ),
        migrations.CreateModel(
            name='MicrolensingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t0', models.FloatField(default=0)),
                ('err_t0', models.FloatField(default=0)),
                ('u0', models.FloatField(default=0)),
                ('err_u0', models.FloatField(default=0)),
                ('tE', models.FloatField(default=0)),
                ('err_tE', models.FloatField(default=0)),
                ('piEN', models.FloatField(default=0)),
                ('err_piEN', models.FloatField(default=0)),
                ('piEE', models.FloatField(default=0)),
                ('err_piEE', models.FloatField(default=0)),
                ('rho', models.FloatField(default=0)),
                ('err_rho', models.FloatField(default=0)),
                ('s', models.FloatField(default=0)),
                ('err_s', models.FloatField(default=0)),
                ('q', models.FloatField(default=0)),
                ('err_q', models.FloatField(default=0)),
                ('alpha', models.FloatField(default=0)),
                ('err_alpha', models.FloatField(default=0)),
                ('source_mag', models.FloatField(default=0)),
                ('err_source_mag', models.FloatField(default=0)),
                ('blend_mag', models.FloatField(default=0)),
                ('err_blend_mag', models.FloatField(default=0)),
            ],
        ),
    ]
