# Generated by Django 4.2.25 on 2025-12-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='prob_master_current',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='prob_master_peak',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_code.galactictarget'),
        ),
        migrations.AddField(
            model_name='microlensingmodel',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_code.galactictarget'),
        ),
        migrations.AddField(
            model_name='microlensingmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
