# Generated by Django 4.2.25 on 2026-01-16 21:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0002_classification_prob_master_current_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'get_latest_by': 'updated_at'},
        ),
        migrations.AlterModelOptions(
            name='microlensingmodel',
            options={'get_latest_by': 'updated_at'},
        ),
        migrations.AlterField(
            model_name='classification',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_parameters', to='custom_code.galactictarget'),
        ),
        migrations.AlterField(
            model_name='microlensingmodel',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microlensing_parameters', to='custom_code.galactictarget'),
        ),
        migrations.CreateModel(
            name='MicrolensingRadarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_fink', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('metric_alerce', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('metric_antares', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('metric_nsquare', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('metric_planet', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('metric_bogus', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('average_master_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rescaled_classification_radar_parameters', to='custom_code.galactictarget')),
            ],
            options={
                'get_latest_by': 'updated_at',
            },
        ),
    ]
