# Generated by Django 4.2.25 on 2026-04-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0003_alter_classification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galactictarget',
            name='expected_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galactictarget',
            name='known_variability',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
