# Generated by Django 4.2.25 on 2026-04-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0004_galactictarget_expected_visits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galactictarget',
            name='expected_visits',
            field=models.IntegerField(default=-1),
        ),
    ]
