# Generated by Django 4.2.25 on 2026-05-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0005_alter_galactictarget_expected_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='galactictarget',
            name='known_extragalactic',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
