# Generated by Django 4.2.25 on 2026-05-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0006_galactictarget_known_extragalactic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galactictarget',
            name='known_extragalactic',
            field=models.CharField(choices=[('not in GLADE+ galaxy catalog', 'Not In Glade Plus'), ('in GLADE+ galaxy catalog', 'In Glade Plus')], max_length=150),
        ),
    ]
