# Generated by Django 5.2.14 on 2026-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0007_alter_galactictarget_known_extragalactic'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='class4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='prob_class4',
            field=models.FloatField(default=0, null=True),
        ),
    ]
