# Generated by Django 5.2.14 on 2026-05-19 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0008_classification_class4_classification_prob_class4'),
    ]

    operations = [
        migrations.AddField(
            model_name='microlensingradardata',
            name='metric_alerce_atat',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=False,
        ),
    ]
