# Generated by Django 5.2.14 on 2026-06-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0010_galactictarget_ztf_baseline_checked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationGeneralized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('probability', models.FloatField(default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='custom_code.galactictarget')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='custom_code.classificationsource')),
            ],
            options={
                'get_latest_by': 'updated_at',
            },
        ),
    ]
