# Generated by Django 5.2.14 on 2026-06-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0011_classificationsource_classificationgeneralized'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationsource',
            name='version',
            field=models.CharField(default='n.a.', max_length=100),
        ),
    ]
