# Generated by Django 5.2.14 on 2026-06-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0012_classificationsource_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationsource',
            name='classifier_name',
            field=models.CharField(default='n.a', max_length=100),
            preserve_default=False,
        ),
    ]
