# Generated by Django 5.2.14 on 2026-06-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0013_classificationsource_classifier_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classificationsource',
            old_name='name',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='classificationsource',
            old_name='publication',
            new_name='classification_origin',
        ),
        migrations.RenameField(
            model_name='classificationsource',
            old_name='version',
            new_name='classifier_version',
        ),
    ]
