# Generated by Django 5.2.14 on 2026-06-29 11:59

import custom_code.target_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0014_rename_name_classificationsource_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseParameterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistical_models', to='custom_code.galactictarget')),
            ],
            options={
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='MicrolensingParameterModel',
            fields=[
                ('baseparametermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='custom_code.baseparametermodel')),
                ('t0', models.FloatField(default=0)),
                ('err_t0', models.FloatField(default=0)),
                ('u0', models.FloatField(default=0)),
                ('err_u0', models.FloatField(default=0)),
                ('tE', models.FloatField(default=0)),
                ('err_tE', models.FloatField(default=0)),
                ('piEN', models.FloatField(default=0)),
                ('err_piEN', models.FloatField(default=0)),
                ('piEE', models.FloatField(default=0)),
                ('err_piEE', models.FloatField(default=0)),
                ('rho', models.FloatField(default=0)),
                ('err_rho', models.FloatField(default=0)),
                ('s', models.FloatField(default=0)),
                ('err_s', models.FloatField(default=0)),
                ('q', models.FloatField(default=0)),
                ('err_q', models.FloatField(default=0)),
                ('alpha', models.FloatField(default=0)),
                ('err_alpha', models.FloatField(default=0)),
                ('source_mag', models.FloatField(default=0)),
                ('err_source_mag', models.FloatField(default=0)),
                ('blend_mag', models.FloatField(default=0)),
                ('err_blend_mag', models.FloatField(default=0)),
            ],
            bases=('custom_code.baseparametermodel',),
        ),
        migrations.CreateModel(
            name='StatisticalModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=custom_code.target_models.image_directory_path)),
                ('statistical_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='custom_code.baseparametermodel')),
            ],
        ),
    ]
