# Generated by Django 5.2.14 on 2026-07-01 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0015_baseparametermodel_microlensingparametermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microlensingradardata',
            name='metric_probability_ratio',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
