# Generated by Django 5.2.14 on 2026-06-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0015_basestatisticalmodel_microlensingstatisticalmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticalmodelimage',
            name='uuid',
        ),
    ]
