# Generated by Django 5.2.14 on 2026-06-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0016_remove_statisticalmodelimage_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basestatisticalmodel',
            options={'get_latest_by': 'updated_at'},
        ),
    ]
